#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'


[[blocks]]
    type = 'prompt'
    alignment = 'left'

    [[blocks.segments]]
        type = 'python'
        style = 'plain'
        template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }}"
        background = ''
        foreground = '#deb896'

        [blocks.segments.properties]
            home_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ .UserName }} '
    background = ''
    foreground = '#BF616A'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    background = ''
    foreground = '#81A1C1'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }}{{ .BranchStatus }} {{ end }}{{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = ''
    foreground = '#6C6C6C'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_ahead_icon = '<#88C0D0>⇡ </>'
      branch_behind_icon = '<#88C0D0>⇣ </>'
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ''


[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    template = ' {{ .FormattedMs }} '
    background = ''
    foreground = '#A3BE8C'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'break'

  [[blocks.segments]]
    type = 'spotify'
    style = 'plain'
    foreground = '#8faf77'

    [blocks.segments.properties]
        playing_icon = " "
        paused_icon = " "
        stopped_icon = " "

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']
    template = '❯ '
    background = ''
    foreground = '#B48EAD'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true


[transient_prompt]
  foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']
  template = '❯ '
  background = ''
  foreground = '#B48EAD'
  Text = ''
  Duration = 0
  NameLength = 0
