console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 3

[transient_prompt]
  template = '❯ '
  foreground = '#B48EAD'
  foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }}'
    foreground = '#deb896'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = '#BF616A'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#81A1C1'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }}{{ .BranchStatus }} {{ end }}{{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#6C6C6C'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_ahead_icon = '<#88C0D0>⇡ </>'
      branch_behind_icon = '<#88C0D0>⇣ </>'
      branch_icon = ''
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = '#A3BE8C'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'break'

  [[blocks.segments]]
    foreground = '#8faf77'
    type = 'spotify'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      paused_icon = ' '
      playing_icon = ' '
      stopped_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = '#B48EAD'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
